### ISSUE TITLE
Invalid signature / v value

### ISSUE THREAD

**Issue by danielnordh** [wakumo/eth-sig-util#13]
I'm attempting to use USDC's `transferWithAuthorization` on a Dart client for submission by a Node.js backend.

**My understanding of the flow so far:**
1. Create typedData
2. Sign typedData using `etc-sig-util`
3. Create ethereum transaction calling USDC `transferWithAuthorization`
4. Sign transaction using `web3dart`
5. Send signed transaction to backend
6. Backend submits the signed transaction

I am currently stuck on step 4, where ethClient.signTransaction gives the following error:
`RPCError: got code 3 with msg "execution reverted: ECRecover: invalid signature 'v' value".`

`v` is from `sigParams.v`, but cast to a `BigInt` as otherwise the `Web3Dart.Transaction.callContract` threw a type error.

Any help figuring out the flow and getting this to work would be appreciated.

**Full code:**

```
Future<String?> signUSDC(BigInt amount, Web3Dart.EthereumAddress ethAddress, User user) async {
    final config = ref.read(configurationProvider).instance;
    final wallet =
        Web3Dart.Wallet.fromJson(user.ethereumWallet!, kWalletPassword);

    final validAfter = BigInt.zero;
    final validBefore = BigInt.from(9223372036854775807);
    final nonce = Nonce.secure(32);
    final nonceBytes = utf8.encode(nonce.toString());

    // 1. Create typed data
    final Map<String, dynamic> rawTypedData = {
      "types": {
        "EIP712Domain": [
          {"name": "name", "type": "string"},
          {"name": "version", "type": "string"},
          {"name": "chainId", "type": "uint256"},
          {"name": "verifyingContract", "type": "address"}
        ],
        "TransferWithAuthorization": [
          {"name": "from", "type": "address"},
          {"name": "to", "type": "address"},
          {"name": "value", "type": "uint256"},
          {"name": "validAfter", "type": "uint256"},
          {"name": "validBefore", "type": "uint256"},
          {"name": "nonce", "type": "bytes32"}
        ]
      },
      "domain": {
        "name": "USDC",
        "version": "2",
        "chainId": config.chain.chainId,
        "verifyingContract": config.chain.usdcContract
      },
      "primaryType": "TransferWithAuthorization",
      "message": {
        "from": user.pubKey,
        "to": ethAddress.toString(),
        "value": amount.toInt(),
        "validAfter": validAfter.toInt(),
        "validBefore": validBefore.toInt(),
        "nonce": nonceBytes.toString()
      }
    };

    // 2. Sign typed data
    String signature = EthSigUtil.signTypedData(
        privateKey: bytesToHex(wallet.privateKey.privateKey),
        jsonData: jsonEncode(rawTypedData),
        version: TypedDataVersion.V4,
        chainId: config.chain.chainId);

    final contract = await ref.read(usdcContractProvider.future);
    var sigParams = SignatureUtil.fromRpcSig(signature);

    // 3. Create transaction calling 'transferWithAuthorization'
    final transaction = Web3Dart.Transaction.callContract(
      contract: contract,
      function: contract.function('transferWithAuthorization'),
      parameters: [
        Web3Dart.EthereumAddress.fromHex(user.pubKey!),
        ethAddress,
        amount,
        validAfter,
        validBefore,
        nonceBytes,
        BigInt.from(sigParams.v),
        bigIntToUint8List(sigParams.r),
        bigIntToUint8List(sigParams.s)
      ],
    );

    // 4. Sign transaction
    final signedTx = await ethClient.signTransaction(
        wallet.privateKey, 
        transaction,
        chainId: config.chain.chainId, 
        fetchChainIdFromNetworkId: false);
    final hexTx = "0x" + hex.encode(signedTx); // not sure if signedTx or hexTx should be used

    // 5. submit signed transaction to backend, get hash in return
    try {
      final body = json.encode((await defaultParams)
        ..addAll({
          "serializedTx": signedTx,
          "validationCode": "[redacted]"
        }));

      return sendRequest(baseUrl.asUri / '[redacted_endpoint]',
          method: DataRequestMethod.POST,
          body: body,
          omitDefaultParams: false, onSuccess: (map) {
        return map['hash'] as String;
      }, onError: (error) {
        return null;
      });
    } catch (error) {
      return null;
    }
  }
```

**Comment by danielnordh** [comment]
The `v` value is wrong, being `42` in this case.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/3393669/153185834-18076dfb-4ff4-4447-926c-1d704a7740fb.png">

If I understand correctly from elsewhere, the v value should be either 27 or 28 for a valid signature.

Does this mean that my EthSigUtil.signTypedData call produces an invalid signature, or that some of the input parameters are bad?

Any thoughts here would be appreciated @ludowkm

**Comment by ludowkm** [comment]
Hi @danielnordh, sorry for late response, i was busy with the current job.
The flow of you is not really correct, from step 2, you should use `TypedDataUtil.hashMessage` to get hash message then you can use sendTransaction from `web3dart` because it will help you to sign and send transaction.
Of course you can you SignTypedData using `etc-sig-util` but then you have to use sendRawTransaction because your message has been signed and you just need to send.
So, for more simple, you just need to change the step 2 to get hash message, please let me know if you get over it or not.

**Comment by danielnordh** [comment]
Thanks for the response @ludowkm 

As I don't want to send the transaction from the mobile client, I don't think using `sendTransaction` will work in this case.
I think I have to use `etc-sig-util`, but as I mentioned it is giving me an invalid `v` value.

Can you see anything in my code that would lead to this? 
It might also be worth returning an error in case of a bad v value as it would mean the signature is incorrect.

**Comment by njovy** [comment]
@danielnordh @ludowkm I am having this issue as well. The library generates an invalid signature.
 I tried to generate a signature using this library and it doesn't generate the one like metamask did.

**Comment by njovy** [comment]
```dart
import 'dart:convert';

import 'package:dappp/src/models/common/part.dart';
import 'package:dappp/src/models/nft/lazy_erc721.dart';
import 'package:dappp/src/models/nft/sign_nft.dart';
import 'package:dappp/web3.dart';
import 'package:eth_sig_util/constant/typed_data_version.dart';
import 'package:eth_sig_util/eth_sig_util.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:web3dart/web3dart.dart';

void main() {
  test('should sign ERC721 nft', () async {
    int chainId = 17;
    String privateKey = "d519f025ae44644867ee8384890c4a0b8a7b00ef844e8d64c566c0ac971c9469";
    Web3()
      ..init(
          privateKey);
    final address = await Web3().credentials().extractAddress();
    final template = LazyErc721(
        contract: EthereumAddress.fromHex(
            '0x2547760120aED692EB19d22A5d9CCfE0f7872fcE'),
        tokenId: BigInt.from(1),
        uri: "ipfs://ipfs/hash",
        creators: [Part.defaultCreator(address)]);
    expect(jsonEncode(template.toJson()),
        r'''{"@type":"ERC721","contract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce","tokenId":"1","uri":"ipfs://ipfs/hash","creators":[{"account":"0xc5eac3488524d577a1495492599e8013b1f91efa","value":10000}],"royalties":[]}''');
    final typedData = jsonEncode(
        SignNft.buildSignData(web3: Web3(), chainId: chainId, nft: template));
    expect(typedData,
        r'''{"types":{"EIP712Domain":[{"type":"string","name":"name"},{"type":"string","name":"version"},{"type":"uint256","name":"chainId"},{"type":"address","name":"verifyingContract"}],"Part":[{"name":"account","type":"address"},{"name":"value","type":"uint96"}],"Mint721":[{"name":"tokenId","type":"uint256"},{"name":"tokenURI","type":"string"},{"name":"creators","type":"Part[]"},{"name":"royalties","type":"Part[]"}]},"domain":{"name":"Mint721","version":"1","chainId":17,"verifyingContract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce"},"primaryType":"Mint721","message":{"@type":"ERC721","contract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce","tokenId":"1","uri":"ipfs://ipfs/hash","creators":[{"account":"0xc5eac3488524d577a1495492599e8013b1f91efa","value":10000}],"royalties":[],"tokenURI":"ipfs://ipfs/hash"}}''');
    final signature = EthSigUtil.signTypedData(privateKey: privateKey, jsonData: typedData, version: TypedDataVersion.V4);
    expect(signature,
        "0xf00568d7564b30239642ba5c81ee7be71e0ca79a64d39dafa2f640e69a3cab2e2ac9ea7df77c23f12af3791d94ce64802c35c79d9553e70f76adda4ca69fd6601c");
  });
}

```
Above is a test code that I used to sign a typed data.
```
Expected: '0xf00568d7564b30239642ba5c81ee7be71e0ca79a64d39dafa2f640e69a3cab2e2ac9ea7df77c23f12af3791d94ce64802c35c79d9553e70f76adda4ca69fd6601c'
  Actual: '0x2d8fa7cf7ea70c0f7a0abf841b41640d1a28f6309c5fdf6657ee4d44682d8b0767d30c268dc1af9b20852071c9a4e7acb916ec0d3c5447bd3818cfbe6170cf831c'
   Which: is different.
          Expected: 0xf00568d756 ...
            Actual: 0x2d8fa7cf7e ...
                      ^
           Differ at offset 2
```
I printed out the expected result from the test code and pasted it here to verify both code uses the same json input. However, the signature isn't same as expected. I believe this library doesn't generate a proper signature.
The mock data is taken from https://github.com/rarible/ethereum-sdk/blob/master/packages/sdk/src/nft/sign-nft.test.ts.

**Comment by njovy** [comment]
```dart
  test('signTypeData', () {
    String privateKey = "d519f025ae44644867ee8384890c4a0b8a7b00ef844e8d64c566c0ac971c9469";
    String json = r'''{"types":{"EIP712Domain":[{"type":"string","name":"name"},{"type":"string","name":"version"},{"type":"uint256","name":"chainId"},{"type":"address","name":"verifyingContract"}],"Part":[{"name":"account","type":"address"},{"name":"value","type":"uint96"}],"Mint721":[{"name":"tokenId","type":"uint256"},{"name":"tokenURI","type":"string"},{"name":"creators","type":"Part[]"},{"name":"royalties","type":"Part[]"}]},"domain":{"name":"Mint721","version":"1","chainId":4,"verifyingContract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce"},"primaryType":"Mint721","message":{"@type":"ERC721","contract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce","tokenId":"1","uri":"ipfs://ipfs/hash","creators":[{"account":"0xc5eac3488524d577a1495492599e8013b1f91efa","value":10000}],"royalties":[],"tokenURI":"ipfs://ipfs/hash"}}''';
    String signature = EthSigUtil.signTypedData(privateKey: privateKey, jsonData: json, version: TypedDataVersion.V4);
    expect(signature, '0xcff6a0055c13a0e7b433f35f2657e66503a79e3261d9b8b6368e20b248666aed7fcebc6419b55b590d3071e7aefc5cad0a0bbf5888fcb3ce38d4ac5545022b521b');
  });
```
Above is a dart code to test signTypedData and the expected result fails.
```js
test("signTypeData", async () => {
        var signature = ethSigUtil.signTypedData_v4(Buffer.from(
            'd519f025ae44644867ee8384890c4a0b8a7b00ef844e8d64c566c0ac971c9469',
            'hex',
        ), {data: domainData})
        expect(signature).toEqual('0xcff6a0055c13a0e7b433f35f2657e66503a79e3261d9b8b6368e20b248666aed7fcebc6419b55b590d3071e7aefc5cad0a0bbf5888fcb3ce38d4ac5545022b521b')
    })
```
Above is a js version and it passes the test.

@ludowkm @danielnordh The library has a severe bug. It just doesn't work as expected so we should avoid using this library at the moment.

**Comment by ludowkm** [comment]
Hi @njovy  , thank you for your report, the current unit test of library did not cover enough cases and there are something wrong, i need to take time to investigate.
Hi @danielnordh , i have just tried your data with js version but look like your format is not correct and it can not output the hash message, but anyway, i need to to fix the above report firstly before continue, sorry for this inconvenience!

**Comment by ludowkm** [comment]
There is something wrong when do abi raw encode, i will try to fix now

**Comment by njovy** [comment]
@ludowkm Thank you for a rapid response.

**Comment by njovy** [comment]
@ludowkm I just created a pull request to fix a issue that an array type is not appended upon generating a hash.

**Comment by ludowkm** [comment]
hi @njovy , thank you so much for the PR, i merged it! Regarding to `ecRecover`, i will prepare unit test later for more detail.
@danielnordh Please upgrade to 0.0.7 and try again!

**Comment by njovy** [comment]
@danielnordh TypedData doesn't contain any array type so I don't think the new version will fix this issue. However there is a byte32 type and I think you should input the same message and generate a signature. Then compare if the signature is same.

**Comment by danielnordh** [comment]
I just tried with the 0.0.7 version and am getting an `ArgumentError (Invalid argument(s): Invalid signature length)` error on: `var sigParams = SignatureUtil.fromRpcSig(signature);`

I am really not sure what about my format is wrong @ludowkm, do you see any obvious errors?

And @njovy when you say "TypedData doesn't contain any array type", are you referring to a particular problem in my code? I'm not sure what might be causing the problem. I have not found any easy to follow examples of the full flow of this USDC function flow.

Thanks both for your time on this issue.

**Comment by ludowkm** [comment]
@danielnordh the current library missed some value assertion so it passed and output wrong signature, in fact, your message is wrong, you can use the js library to debug which one is wrong. In the future, i will improve the current library better. So now, please correct your message firstly.

**Comment by danielnordh** [comment]
So it seems that using chainId produces an invalid signature/length with this library, see #15.
Meanwhile, I am trying to debug my message in the js library by [metamask](https://github.com/MetaMask/eth-sig-util) as suggested by @ludowkm, with this simple js code (for a test case):

```
const ethSigUtil = require("@metamask/eth-sig-util");
const { SignTypedDataVersion } = require("@metamask/eth-sig-util");

const privateKey = '4af1bceebf7f3634ec3cff8a2c38e51178d5d4ce585c52d6043e5e2cc3418bb0';
const msgParamsOg = {"types":{"EIP712Domain":[{"type":"string","name":"name"},{"type":"string","name":"version"},{"type":"uint256","name":"chainId"},{"type":"address","name":"verifyingContract"}],"Part":[{"name":"account","type":"address"},{"name":"value","type":"uint96"}],"Mint721":[{"name":"tokenId","type":"uint256"},{"name":"tokenURI","type":"string"},{"name":"creators","type":"Part[]"},{"name":"royalties","type":"Part[]"}]},"domain":{"name":"Mint721","version":"1","chainId":4,"verifyingContract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce"},"primaryType":"Mint721","message":{"@type":"ERC721","contract":"0x2547760120aed692eb19d22a5d9ccfe0f7872fce","tokenId":"1","uri":"ipfs://ipfs/hash","creators":[{"account":"0xc5eac3488524d577a1495492599e8013b1f91efa","value":10000}],"royalties":[],"tokenURI":"ipfs://ipfs/hash"}};
  
let msgParams = JSON.stringify(msgParamsOg);
let version = SignTypedDataVersion.V4;

const signature = ethSigUtil.signTypedData(privateKey, msgParams, version);
console.log("Signature: " + signature);
```

But I can't seem to get that to work due to the following error:
`Error: Invalid version: 'undefined'`

Do you mind sharing what js library you used to test the message, or if I'm making a basic mistake in my code above?

**Comment by kabaneridev** [comment]
hey @danielnordh, I asked you in the other ticket about this, but if you don't mind, could you please share your working example in JS?
