### ISSUE TITLE
signMessage do not use privateKeyInBytes when calling SignatureUtil.sign

### ISSUE THREAD

**Issue by jvinai** [wakumo/eth-sig-util#21]
I want to use `EthSigUtil.signMessage` using `privateKeyInBytes` parameter but, in the source code, it's not used when calling `SignatureUtil.sign`.

Source code:
```
  static String signMessage(
      {String? privateKey,
      Uint8List? privateKeyInBytes,
      required Uint8List message}) {
    return SignatureUtil.sign(message: message, privateKey: privateKey);
  }
```

Edit: After looking at the source code of many functions, a looooot of them are not using `privateKeyInBytes`.

**Comment by ludowkm** [comment]
Thank you @jvinai for your report, i fixed on 0.0.9, let's use it <3
