### ISSUE TITLE
 Could not construct a recoverable key. This should never happen

### ISSUE THREAD

**Issue by FZ985** [wakumo/eth-sig-util#8]
final private =
        EthPrivateKey.fromHex(WalletSp.instance.getCurrentPrivateKey());

final data = 'hello 哈哈';

final sign1 = EthSigUtil.signPersonalMessage(privateKey: bytesToHex(private.privateKey),message: Uint8List.fromList(utf8.encode(data)));

logger('sign1:$sign1');

---------------------------------------------------------------------------------

**I reported this error by calling the signPersonalMessage function**

**Comment by ludowkm** [comment]
hi @FZ985 , thank you for your report, i have just fixed it and publish 0.0.5, let's use it to solve your issue!
